### PR TITLE
Update zerossl-bot.sh

### PR DESCRIPTION
**Pull request by Blackbam**
Issue with arguments caused some to issue with wrong CA

### CODE REVIEW

**Review by bitroniq — APPROVED** [review]
Looks good!

**Comment by peterwilli** [comment]
You sure this is good? Since I run from `master`, I get the following error with a DNS authentication hook (sensitive information removed):

```
technitium-dns_manager_server-1  | [2023-08-31T17:07:46Z DEBUG dns_manager_server::routes::dns_manager] CMD: cd "/tmp/.tmpAvP58B" && "zerossl-bot" "--zerossl-api-key=<zerossl_api_key>" "certonly" "--csr=csr.txt" "--config-dir=/var/certbot/config" "--logs-dir=/var/certbot/logs" "--work-dir=/var/certbot/work" "--manual" "--agree-tos" "--email=<email>" "-n" "--manual-public-ip-logging-ok" "--preferred-challenges=dns" "--manual-auth-hook=/usr/local/bin/dns-manager-server -z ion.ooo -t <api key> --email \'<email>\' --dns-endpoint \'http://technitium:5380/\' authentication-hook"
technitium-dns_manager_server-1  | [2023-08-31T17:07:49Z DEBUG dns_manager_server::routes::dns_manager] CMD stdout: certonly --csr=csr.txt --config-dir=/var/certbot/config --logs-dir=/var/certbot/logs --work-dir=/var/certbot/work --manual --agree-tos --email=<email> -n --manual-public-ip-logging-ok --preferred-challenges=dns --manual-auth-hook=/usr/local/bin/dns-manager-server -z ion.ooo -t <api key> --email '<email>' --dns-endpoint 'http://technitium:5380/' authentication-hook --eab-kid KIAEht_UuI9dasZUJJQAOw --eab-hmac-key <key> --server https://acme.zerossl.com/v2/DV90
technitium-dns_manager_server-1  |      stderr: usage: 
technitium-dns_manager_server-1  |       certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...
technitium-dns_manager_server-1  |     
technitium-dns_manager_server-1  |     Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
technitium-dns_manager_server-1  |     it will attempt to use a webserver both for obtaining and installing the
technitium-dns_manager_server-1  |     certificate. 
technitium-dns_manager_server-1  |     certbot: error: unrecognized arguments: -z ion.ooo <api key> --dns-endpoint 'http://technitium:5380/' authentication-hook
technitium-dns_manager_server-1  |     
```

I believe https://github.com/zerossl/zerossl-bot/pull/25 is the right way to do it. Why is it reverted?

**Comment by bitroniq** [comment]
@peterwilli you provided the wrong ARGs. The goal for this PR and my issue https://github.com/zerossl/zerossl-bot/issues/33 was to use the `${CERTBOT_ARGS[@]}` instead of `ARGS` for `certbot`.

Make sure your `zerossl-bot.sh` has in the last line

```
certbot ${CERTBOT_ARGS[@]}
```

**Comment by peterwilli** [comment]
> Make sure your `zerossl-bot.sh` has in the last line

Thanks for replying so soon! I used `bash <(curl -s https://zerossl.com/get-zerosslbot.sh)`, which pulls from `master` (so all the merged PR's should've been in there). I still got the error message above.

Also, running `curl https://raw.githubusercontent.com/zerossl/zerossl-bot/master/zerossl-bot.sh` shows the last line you mentioned.

**Pull request merged**
